image:
  repository: spondifereye/terrace-of-seeds
  tag: 0.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 7777
  metallb:
    enabled: true
    ip: "192.168.4.55"

persistence:
  size: 1Gi
  storageClass: "longhorn-retain"

world:
  path: /world
  filename: world.wld

